### ISSUE TITLE
[Bug] SSL Pinning bypass stopped working after latest TikTok update

### ISSUE THREAD

**Issue by dellus1on** [Eltion/Tiktok-SSL-Pinning-Bypass#54]
**Describe the bug**
The latest patched APK (v31.5.3) with SSL pinning bypass has stopped working as of a few days ago. It seems like TikTok has updated their SSL pinning method, making the bypass ineffective

**App info**
 - Version: tiktok-v31.5.3
 - Arch: x86, x86_64, armeabi-v7a, arm64-v8a

**Device info**
- Model: Xiaomi Mi10T
- Android Version: 13

**Proxy tool**
http toolkit: v1.14.11
burp: v2023.10.2.4

**Logs**
Unfortunately, there are no specific logs, but the app appears to not send or receive any data through the proxy when SSL pinning is bypassed. I can provide detailed logs from Burp Suite if needed.

**Additional context**
Would it be possible to release an updated version of the APK with the new SSL pinning bypass? It seems like TikTok has changed their security method for SSL pinning. Thank you for your hard work on this project!

**Comment by Eltion** [comment]
Should be fixed in the new released version

**Comment by johnkim2000** [comment]
Hi Eltion, I just tried v.37.0.4, and it still doesn't seem to work.  Has it worked for others?

**Comment by johnkim2000** [comment]
Hi Eltion, I just tried v.37.0.4, and it still doesn't seem to work.  Has it worked for others?

**Comment by dellus1on** [comment]
> Hi Eltion, I just tried v.37.0.4, and it still doesn't seem to work. Has it worked for others?

also don`t work for me without root, with root work correctly

**Comment by StraightouttaIG** [comment]
> Hi Eltion, I just tried v.37.0.4, and it still doesn't seem to work. Has it worked for others?

Same here. I can intercept other Apps fine but when I launch the patched APK the app says "No internet connection" 

I reinstalled Burpsuite certifcate and made a new Memu instance but still whenever I try to intercept traffic it says "No internet connection"
